# Picom configuration file

backend = "glx";
vsync = true;

shadow = true;
shadow-radius = 10;
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-opacity = 0.5;
shadow-exclude = [
  "class_g = 'Notification'",
  "class_g = 'Mugshot'"
];

opacity-rule = [
  "90:class_g = 'XTerm'",
  "85:class_g = 'URxvt'"
];

fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;

active-opacity = 0.9;
inactive-opacity = 0.7;

